apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cowweb
  name: cowweb
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: cowweb
  template:
    metadata:
      labels:
        app: cowweb
    spec:
      containers:
        - name: cowweb
          image: ghcr.io/hhiroshell/cowweb-go/cowweb:v1.0.0
          command: 
            - ./cowweb
          args:
            - serve
            - --port=8080
            - --slow
            - --load=128
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /say
              port: api
            initialDelaySeconds: 1
            periodSeconds: 1
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"